name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 或者你的默认分支，比如 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '8.19.1' # 选择你项目需要的 Node.js 版本

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # GitHub Pages 分支
        folder: dist # Vite 构建输出目录
        token: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动创建的令牌，用于授权
