name: Deploy via Script

on:
  push:
    branches:
      - main # 或您的主分支名，如 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # 根据 deploy.sh 需要的 Node.js 版本调整

    - name: Install dependencies
      run: npm install

    - name: Execute deploy script
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
      env:
        CI: true
