name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 您的默认分支可能是 main 或 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '8.19.1' # 选择您需要的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build # 或者您项目中用于构建的命令

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # 部署到 gh-pages 分支
        folder: dist # 或您构建的输出目录
